/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const InquiryId = IDL.Nat;
export const IdolCategory = IDL.Variant({
  'EcoFriendly' : IDL.Null,
  'Clay' : IDL.Null,
  'Fiber' : IDL.Null,
  'Metal' : IDL.Null,
  'PlasterOfParis' : IDL.Null,
  'Marble' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateIdolInput = IDL.Record({
  'stockQuantity' : IDL.Nat,
  'heightCm' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IdolCategory,
  'price' : IDL.Nat,
  'material' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const IdolId = IDL.Nat;
export const Idol = IDL.Record({
  'id' : IdolId,
  'stockQuantity' : IDL.Nat,
  'heightCm' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IdolCategory,
  'price' : IDL.Nat,
  'material' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const Inquiry = IDL.Record({
  'id' : InquiryId,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'idolName' : IDL.Text,
  'preferredContact' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'idolId' : IdolId,
});
export const SubmitInquiryInput = IDL.Record({
  'customerName' : IDL.Text,
  'email' : IDL.Text,
  'idolName' : IDL.Text,
  'preferredContact' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'idolId' : IdolId,
});
export const UpdateIdolInput = IDL.Record({
  'id' : IdolId,
  'stockQuantity' : IDL.Nat,
  'heightCm' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IdolCategory,
  'price' : IDL.Nat,
  'material' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'archiveInquiry' : IDL.Func([InquiryId], [IDL.Bool], []),
  'categoryToText' : IDL.Func([IdolCategory], [IDL.Text], ['query']),
  'createIdol' : IDL.Func([CreateIdolInput], [Idol], []),
  'deleteIdol' : IDL.Func([IdolId], [IDL.Bool], []),
  'getIdol' : IDL.Func([IdolId], [IDL.Opt(Idol)], ['query']),
  'listAllIdols' : IDL.Func([], [IDL.Vec(Idol)], ['query']),
  'listIdols' : IDL.Func([], [IDL.Vec(Idol)], ['query']),
  'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'markInquiryRead' : IDL.Func([InquiryId], [IDL.Bool], []),
  'submitInquiry' : IDL.Func([SubmitInquiryInput], [Inquiry], []),
  'textToCategory' : IDL.Func([IDL.Text], [IDL.Opt(IdolCategory)], ['query']),
  'updateIdol' : IDL.Func([UpdateIdolInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const InquiryId = IDL.Nat;
  const IdolCategory = IDL.Variant({
    'EcoFriendly' : IDL.Null,
    'Clay' : IDL.Null,
    'Fiber' : IDL.Null,
    'Metal' : IDL.Null,
    'PlasterOfParis' : IDL.Null,
    'Marble' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateIdolInput = IDL.Record({
    'stockQuantity' : IDL.Nat,
    'heightCm' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IdolCategory,
    'price' : IDL.Nat,
    'material' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const IdolId = IDL.Nat;
  const Idol = IDL.Record({
    'id' : IdolId,
    'stockQuantity' : IDL.Nat,
    'heightCm' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IdolCategory,
    'price' : IDL.Nat,
    'material' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Inquiry = IDL.Record({
    'id' : InquiryId,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'idolName' : IDL.Text,
    'preferredContact' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'idolId' : IdolId,
  });
  const SubmitInquiryInput = IDL.Record({
    'customerName' : IDL.Text,
    'email' : IDL.Text,
    'idolName' : IDL.Text,
    'preferredContact' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'idolId' : IdolId,
  });
  const UpdateIdolInput = IDL.Record({
    'id' : IdolId,
    'stockQuantity' : IDL.Nat,
    'heightCm' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IdolCategory,
    'price' : IDL.Nat,
    'material' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'archiveInquiry' : IDL.Func([InquiryId], [IDL.Bool], []),
    'categoryToText' : IDL.Func([IdolCategory], [IDL.Text], ['query']),
    'createIdol' : IDL.Func([CreateIdolInput], [Idol], []),
    'deleteIdol' : IDL.Func([IdolId], [IDL.Bool], []),
    'getIdol' : IDL.Func([IdolId], [IDL.Opt(Idol)], ['query']),
    'listAllIdols' : IDL.Func([], [IDL.Vec(Idol)], ['query']),
    'listIdols' : IDL.Func([], [IDL.Vec(Idol)], ['query']),
    'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'markInquiryRead' : IDL.Func([InquiryId], [IDL.Bool], []),
    'submitInquiry' : IDL.Func([SubmitInquiryInput], [Inquiry], []),
    'textToCategory' : IDL.Func([IDL.Text], [IDL.Opt(IdolCategory)], ['query']),
    'updateIdol' : IDL.Func([UpdateIdolInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };