/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateIdolInput {
  'stockQuantity' : bigint,
  'heightCm' : bigint,
  'name' : string,
  'description' : string,
  'category' : IdolCategory,
  'price' : bigint,
  'material' : string,
  'images' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export interface Idol {
  'id' : IdolId,
  'stockQuantity' : bigint,
  'heightCm' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'category' : IdolCategory,
  'price' : bigint,
  'material' : string,
  'images' : Array<ExternalBlob>,
}
export type IdolCategory = { 'EcoFriendly' : null } |
  { 'Clay' : null } |
  { 'Fiber' : null } |
  { 'Metal' : null } |
  { 'PlasterOfParis' : null } |
  { 'Marble' : null };
export type IdolId = bigint;
export interface Inquiry {
  'id' : InquiryId,
  'customerName' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'email' : string,
  'idolName' : string,
  'preferredContact' : string,
  'message' : string,
  'phone' : string,
  'idolId' : IdolId,
}
export type InquiryId = bigint;
export interface SubmitInquiryInput {
  'customerName' : string,
  'email' : string,
  'idolName' : string,
  'preferredContact' : string,
  'message' : string,
  'phone' : string,
  'idolId' : IdolId,
}
export interface UpdateIdolInput {
  'id' : IdolId,
  'stockQuantity' : bigint,
  'heightCm' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : IdolCategory,
  'price' : bigint,
  'material' : string,
  'images' : Array<ExternalBlob>,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'archiveInquiry' : ActorMethod<[InquiryId], boolean>,
  'categoryToText' : ActorMethod<[IdolCategory], string>,
  'createIdol' : ActorMethod<[CreateIdolInput], Idol>,
  'deleteIdol' : ActorMethod<[IdolId], boolean>,
  'getIdol' : ActorMethod<[IdolId], [] | [Idol]>,
  'listAllIdols' : ActorMethod<[], Array<Idol>>,
  'listIdols' : ActorMethod<[], Array<Idol>>,
  'listInquiries' : ActorMethod<[], Array<Inquiry>>,
  'markInquiryRead' : ActorMethod<[InquiryId], boolean>,
  'submitInquiry' : ActorMethod<[SubmitInquiryInput], Inquiry>,
  'textToCategory' : ActorMethod<[string], [] | [IdolCategory]>,
  'updateIdol' : ActorMethod<[UpdateIdolInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];