/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Idol {
    id: IdolId;
    stockQuantity: bigint;
    heightCm: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    category: IdolCategory;
    price: bigint;
    material: string;
    images: Array<ExternalBlob>;
}
export interface CreateIdolInput {
    stockQuantity: bigint;
    heightCm: bigint;
    name: string;
    description: string;
    category: IdolCategory;
    price: bigint;
    material: string;
    images: Array<ExternalBlob>;
}
export type InquiryId = bigint;
export type IdolId = bigint;
export interface SubmitInquiryInput {
    customerName: string;
    email: string;
    idolName: string;
    preferredContact: string;
    message: string;
    phone: string;
    idolId: IdolId;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Inquiry {
    id: InquiryId;
    customerName: string;
    createdAt: bigint;
    isRead: boolean;
    email: string;
    idolName: string;
    preferredContact: string;
    message: string;
    phone: string;
    idolId: IdolId;
}
export interface UpdateIdolInput {
    id: IdolId;
    stockQuantity: bigint;
    heightCm: bigint;
    name: string;
    description: string;
    isActive: boolean;
    category: IdolCategory;
    price: bigint;
    material: string;
    images: Array<ExternalBlob>;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum IdolCategory {
    EcoFriendly = "EcoFriendly",
    Clay = "Clay",
    Fiber = "Fiber",
    Metal = "Metal",
    PlasterOfParis = "PlasterOfParis",
    Marble = "Marble"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    archiveInquiry(id: InquiryId): Promise<boolean>;
    categoryToText(cat: IdolCategory): Promise<string>;
    createIdol(input: CreateIdolInput): Promise<Idol>;
    deleteIdol(id: IdolId): Promise<boolean>;
    getIdol(id: IdolId): Promise<Idol | null>;
    listAllIdols(): Promise<Array<Idol>>;
    listIdols(): Promise<Array<Idol>>;
    listInquiries(): Promise<Array<Inquiry>>;
    markInquiryRead(id: InquiryId): Promise<boolean>;
    submitInquiry(input: SubmitInquiryInput): Promise<Inquiry>;
    textToCategory(text: string): Promise<IdolCategory | null>;
    updateIdol(input: UpdateIdolInput): Promise<boolean>;
}
import type { CreateIdolInput as _CreateIdolInput, ExternalBlob as _ExternalBlob, Idol as _Idol, IdolCategory as _IdolCategory, IdolId as _IdolId, UpdateIdolInput as _UpdateIdolInput, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async archiveInquiry(arg0: InquiryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveInquiry(arg0);
            return result;
        }
    }
    async categoryToText(arg0: IdolCategory): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.categoryToText(to_candid_IdolCategory_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.categoryToText(to_candid_IdolCategory_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createIdol(arg0: CreateIdolInput): Promise<Idol> {
        if (this.processError) {
            try {
                const result = await this.actor.createIdol(await to_candid_CreateIdolInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Idol_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIdol(await to_candid_CreateIdolInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Idol_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteIdol(arg0: IdolId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIdol(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIdol(arg0);
            return result;
        }
    }
    async getIdol(arg0: IdolId): Promise<Idol | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdol(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdol(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllIdols(): Promise<Array<Idol>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllIdols();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllIdols();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listIdols(): Promise<Array<Idol>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIdols();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIdols();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInquiries();
            return result;
        }
    }
    async markInquiryRead(arg0: InquiryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markInquiryRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markInquiryRead(arg0);
            return result;
        }
    }
    async submitInquiry(arg0: SubmitInquiryInput): Promise<Inquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0);
            return result;
        }
    }
    async textToCategory(arg0: string): Promise<IdolCategory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.textToCategory(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.textToCategory(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateIdol(arg0: UpdateIdolInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIdol(await to_candid_UpdateIdolInput_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIdol(await to_candid_UpdateIdolInput_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_IdolCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdolCategory): IdolCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_Idol_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Idol): Promise<Idol> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Idol]): Promise<Idol | null> {
    return value.length === 0 ? null : await from_candid_Idol_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IdolCategory]): IdolCategory | null {
    return value.length === 0 ? null : from_candid_IdolCategory_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _IdolId;
    stockQuantity: bigint;
    heightCm: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    category: _IdolCategory;
    price: bigint;
    material: string;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: IdolId;
    stockQuantity: bigint;
    heightCm: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    category: IdolCategory;
    price: bigint;
    material: string;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        stockQuantity: value.stockQuantity,
        heightCm: value.heightCm,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        category: from_candid_IdolCategory_n16(_uploadFile, _downloadFile, value.category),
        price: value.price,
        material: value.material,
        images: await from_candid_vec_n18(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    EcoFriendly: null;
} | {
    Clay: null;
} | {
    Fiber: null;
} | {
    Metal: null;
} | {
    PlasterOfParis: null;
} | {
    Marble: null;
}): IdolCategory {
    return "EcoFriendly" in value ? IdolCategory.EcoFriendly : "Clay" in value ? IdolCategory.Clay : "Fiber" in value ? IdolCategory.Fiber : "Metal" in value ? IdolCategory.Metal : "PlasterOfParis" in value ? IdolCategory.PlasterOfParis : "Marble" in value ? IdolCategory.Marble : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Idol>): Promise<Array<Idol>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Idol_n14(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateIdolInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateIdolInput): Promise<_CreateIdolInput> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_IdolCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IdolCategory): _IdolCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateIdolInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateIdolInput): Promise<_UpdateIdolInput> {
    return await to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockQuantity: bigint;
    heightCm: bigint;
    name: string;
    description: string;
    category: IdolCategory;
    price: bigint;
    material: string;
    images: Array<ExternalBlob>;
}): Promise<{
    stockQuantity: bigint;
    heightCm: bigint;
    name: string;
    description: string;
    category: _IdolCategory;
    price: bigint;
    material: string;
    images: Array<_ExternalBlob>;
}> {
    return {
        stockQuantity: value.stockQuantity,
        heightCm: value.heightCm,
        name: value.name,
        description: value.description,
        category: to_candid_IdolCategory_n8(_uploadFile, _downloadFile, value.category),
        price: value.price,
        material: value.material,
        images: await to_candid_vec_n12(_uploadFile, _downloadFile, value.images)
    };
}
async function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: IdolId;
    stockQuantity: bigint;
    heightCm: bigint;
    name: string;
    description: string;
    isActive: boolean;
    category: IdolCategory;
    price: bigint;
    material: string;
    images: Array<ExternalBlob>;
}): Promise<{
    id: _IdolId;
    stockQuantity: bigint;
    heightCm: bigint;
    name: string;
    description: string;
    isActive: boolean;
    category: _IdolCategory;
    price: bigint;
    material: string;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        stockQuantity: value.stockQuantity,
        heightCm: value.heightCm,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        category: to_candid_IdolCategory_n8(_uploadFile, _downloadFile, value.category),
        price: value.price,
        material: value.material,
        images: await to_candid_vec_n12(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IdolCategory): {
    EcoFriendly: null;
} | {
    Clay: null;
} | {
    Fiber: null;
} | {
    Metal: null;
} | {
    PlasterOfParis: null;
} | {
    Marble: null;
} {
    return value == IdolCategory.EcoFriendly ? {
        EcoFriendly: null
    } : value == IdolCategory.Clay ? {
        Clay: null
    } : value == IdolCategory.Fiber ? {
        Fiber: null
    } : value == IdolCategory.Metal ? {
        Metal: null
    } : value == IdolCategory.PlasterOfParis ? {
        PlasterOfParis: null
    } : value == IdolCategory.Marble ? {
        Marble: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
